export enum ActionTypes {
  ADDTOCART = "ADDTOCART",
  REMOVEFROMCART = "REMOVEFROMCART",
  CLEARCART = "CLEARCART",
  GETPARSEDCOOKIE = "GETPARSEDCOOKIE",

  SEARCHINGFILTER = 'SEARCHINGFILTER',
  CATEGORY_FILTER = 'CATEGORY_FILTER',

  AUTH = "AUTH",

  NOTIFY = "NOTIFY",
  ADD_CART = "ADD_CART",
  ADD_MODAL = "ADD_MODAL",
  ADD_ORDERS = "ADD_ORDERS",
  ADD_USERS = "ADD_USERS",
  ADD_CATEGORIES = "ADD_CATEGORIES",
}

// *TENGO Q USARLO?* export const getParsedCookie = 'addToCart'
