name: CI/CD Frontend Bigpixel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  deploys:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Creating image
        run: |
            echo "Making pull..."
            cd /home/Frontend-bp/bp-frontend/
            git pull

      - name: Deploy Frontend
        run: |
            echo "Making deploy..."
            cd /home/Frontend-bp/bp-frontend/
            docker-compose down -v
            docker-compose build --no-cache
            docker-compose up -d