name: CI/CD Frontend Bigpixel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  deploys:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
